
[project]
site_name = "FedRAMP Legacy Documentation"
site_description = "Legacy documentation by FedRAMP, available for reference only during the transition to the Consolidated Rules for 2026."
site_author = "pete@fedramp.gov"
site_dir = "html/"
docs_dir = "content/"
site_url = "https://www.fedramp.gov/legacy/"
repo_url = "https://github.com/fedramp/docs-legacy"
repo_name = "FedRAMP/docs-legacy"
nav = [
    { "Legacy FedRAMP Documentation Reference" = [
        "index.md",
        { "Cloud Service Providers" = [
            "playbook/csp/index.md",
            { "Getting Started" = [
                "playbook/csp/authorization/getting-started.md",
                { "Rev5 Authorization" = "playbook/csp/authorization/agency-authorization-path.md" },
                { "Partners" = "playbook/csp/authorization/partners.md" },
                { "Important Considerations" = "playbook/csp/authorization/considerations.md" },
            ] },
            { "Rev5 Authorization Packages" = [
                "playbook/csp/authorization/what.md",
                { "Roles & Responsibilities" = "playbook/csp/authorization/roles.md" },
                { "System Security Plan (SSP)" = "playbook/csp/authorization/ssp.md" },
                { "Security Assessment Plan (SAP)" = "playbook/csp/authorization/sap.md" },
                { "Security Assessment Report (SAR)" = "playbook/csp/authorization/sar.md" },
                { "Plans of Action & Milestones" = "playbook/csp/authorization/poam.md" },
            ] },
            { "Continuous Monitoring" = [
                "playbook/csp/continuous-monitoring/intro.md",
                { "Overview of Expectations" = "playbook/csp/continuous-monitoring/overview.md" },
                { "Vulnerability Scanning" = "playbook/csp/continuous-monitoring/vulnerability-scanning.md" },
                { "Annual Assessment" = "playbook/csp/continuous-monitoring/annual-assessment.md" },
                { "Significant Changes" = "playbook/csp/continuous-monitoring/significant-changes.md" },
                { "Incident Communication" = "playbook/csp/continuous-monitoring/incident-communication.md" },
                { "Collaborative ConMon" = "playbook/csp/continuous-monitoring/collaborative-monitoring.md" },
                { "Performance Management" = "playbook/csp/continuous-monitoring/performance-management.md" },
            ] },
        ] },
        { "Agencies" = [
            { "The FedRAMP Marketplace" = "playbook/agency/authorization/marketplace.md" },
            { "Sponsoring Authorizations" = "playbook/agency/authorization/sponsoring.md" },
            { "Preparation" = "playbook/agency/authorization/preparation.md" },
            { "Authorization" = "playbook/agency/authorization/authorization.md" },
            { "Continuous Monitoring" = "playbook/agency/authorization/continuous-monitoring.md" },
        ] },
    ] },
    { "--> go to Consolidated Rules for 2026" = "/2026" },
    { "--> return to FedRAMP.gov" = "/" },
]
extra_javascript = ["https://www.fedramp.gov/javascripts/dap.js"]    # Shim for Digital Analytics Program (DAP)
copyright = "fedramp.gov"

[project.extra]
homepage = "/legacy"
social_image = "assets/secondary_logo.png"
social_image_alt = "FedRAMP Legacy Documentation Reference"


[project.extra.analytics]
provider = "google"
property = "G-E1PPDRDY5R"

[project.extra.analytics.feedback]
title = "Was this page helpful?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "This page was helpful"
data = 1
note = "Thanks for your feedback!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "This page could be improved"
data = 0
note = "Thanks for your feedback!"


[project.theme]
custom_dir = "overrides"
logo = "assets/secondary_logo.png"
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  #"navigation.expand",
  "search.highlight",
  "toc.follow",
  #"toc.integrate",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.theme.icon.admonition]
abstract = "fontawesome/solid/gavel"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
tables = {}

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
